#!/bin/bash

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

TMPDIR=

onexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		rm -rf $TMPDIR
	fi
}

PACKAGE_NAME=tigervnc
VERSION=1.16.80
BUILD=
SRCDIR=/workspace
BINDIR=/workspace/build-linux
OS=Linux
CPU=x86_64
PREFIX=/usr/local
CFLAGS=" -std=gnu99 -Wall -Wextra -Wformat=2 -Wvla"
if [[ $CFLAGS = *-m32* ]]; then
	CPU=i686
fi
PACKAGE_FILE=$PACKAGE_NAME-$OS-$CPU-$VERSION.tar.gz

cd $BINDIR

umask 022
TMPDIR=`mktemp -d /tmp/$PACKAGE_NAME-build.XXXXXX`
rm -f $PACKAGE_FILE
OUTDIR=$TMPDIR/inst/$PREFIX

mkdir -p $OUTDIR/bin
mkdir -p $OUTDIR/man/man1

make DESTDIR=$TMPDIR/inst install

pushd $TMPDIR/inst
tar cfz ../$PACKAGE_FILE .
popd
cp $TMPDIR/$PACKAGE_FILE .

exit
